// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:025dea08-bfd7-4401-ae8d-e295bb2319bc",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_k7Pe93q7E",
    "aws_user_pools_web_client_id": "177798abkrk5s7h7kqtlhhd7sk"
};


export default awsmobile;
