// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:39e5d2b8-b735-415a-b408-75abef61cc62",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xAHQPTvkJ",
    "aws_user_pools_web_client_id": "4f6hb292pf7ibo1qh7qrjqjce5",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "info-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "city-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "postcard-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "user-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "friendrequest-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "friendship-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "achievement-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "visitedCity-dev",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "circleapp-postcareimage-dev-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "circleApp",
            "endpoint": "https://pypg9h4lxe.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
